### ISSUE TITLE
Interpolation settings get saved between sessions, even when replaying a log file

### ISSUE THREAD

**Issue by JoachimCoenen** [scgmlz/Steca#126]
That can cause Steca to behave differently when replaying a log file and the interpolation settings have been changed between recording the log file and replaying it (even if the app is restarted ). (or when the log itself changes the interpolation settings).

**Comment by jwuttke** [comment]
We to log when widgets/cells are changed while settings are loaded.

**Comment by JoachimCoenen** [comment]
> We to log when widgets/cells are changed while settings are loaded.

adding this is non-trivial, bc currently have _no_ logging/replay functionality.
