### ISSUE TITLE
Steca sometimes crashes, when changing normalization source

### ISSUE THREAD

**Issue by JoachimCoenen** [scgmlz/Steca#142]
when changing normalization source (eg. delta Time, or Monitor) to a source for which some clusters have invalid data (eg. -1 or NaN, etc...) the program crashes.

**Comment by JoachimCoenen** [comment]
see also #143.

**Comment by JoachimCoenen** [comment]
I cannot get the program to crash any more. fixed?

**Comment by jwuttke** [comment]
reopen if the problem reappears
