### ISSUE TITLE
bug in calculation of Jacobian matrix of gaussian peak function

### ISSUE THREAD

**Issue by JoachimCoenen** [scgmlz/Steca#155]
`*Jacobian++ = inten*g*(dx)/SQR(stdv);`
gets expanded into (`SQR(x)` is a macro ):
`*Jacobian++ = inten*g*(dx)/(stdv)*(stdv);`
which equals:
`*Jacobian++ = inten*g*dx;`
it should be:
`*Jacobian++ = inten*g*dx/(stdv*stdv);`
Proposed fix:
make `SQR(x)` a proper function.
this considerably increases the performance of fitting the Gaussian (and might lead to better fit results).

**Comment by jwuttke** [comment]
Bad bug indeed, good that you found it.
Defining SQR as a macro, however, is good practice.
We just need to do it the right way, namely
#define SQR(x) ((x)*(x))

**Comment by JoachimCoenen** [comment]
why is it good practice?
