### ISSUE TITLE
Error when launching the application

### ISSUE THREAD

**Issue by probonopd** [scgmlz/Steca#168]
This is what we get when we run the AppImage on Ubuntu 14.04 without internet access:

![](https://github.com/AppImage/appimage.github.io/blob/5e744efe26432a0b0c0f3337be25bc2d70c78542/database/Steca/screenshot.png?raw=true)

Reference:
https://github.com/AppImage/appimage.github.io/pull/683#issuecomment-422480802

**Comment by JoachimCoenen** [comment]
I cannot recreate this on ubuntu 16.04 LTS and the newest state on [scgmlz/develop](https://github.com/scgmlz/Steca/tree/develop). I'll try to recreate this bug using the version used in the [pull request](https://github.com/AppImage/appimage.github.io/pull/683).

**Comment by JoachimCoenen** [comment]
bug successfully recreated. I'll fix it now.

**Comment by probonopd** [comment]
Kindly let me know once a fixed version is available on https://github.com/scgmlz/Steca/releases so that I can include it in the AppImageHub central directory of available AppImages, thanks.
