### ISSUE TITLE
improve visuals of "enable correction file"-button

### ISSUE THREAD

**Issue by JoachimCoenen** [scgmlz/Steca#197]
It is easily missed when looking for an on/off switch for the correction file. Maybe use something like an "on"/"off" button instead of the check-mark currently used.

**Comment by JoachimCoenen** [comment]
eg:
![screenshot from 2018-09-24 15-07-57](https://user-images.githubusercontent.com/29330338/45954261-d4f88f00-c00c-11e8-9dae-455a1cf9f8d9.png)

**Comment by jwuttke** [comment]
won't do unless required by users
