### ISSUE TITLE
reimplement intensity array to avoid divisions in element access

### ISSUE THREAD

**Issue by jwuttke** [scgmlz/Steca#59]
use 1D vector ... should accelerate core computation

handle ScatteringDirection without Array2D, specialize Array2D to float

**Comment by jwuttke** [comment]
resolved on 19apr

**Comment by ghost** [comment]
Intensity array used use a 1D vector, initially. It had been changed to the, at the first glance less efficient 2D structure with separately allocated rows (or columns?) and indirection in accessing the data, for a good reason: when processing X-ray data (4K * 4K, I vaguely recall), there were memory allocation failures on one of the Windows 7 (TUM) machines (that has a different graphics card than the others). Splitting the allocation of a single memory block to  a number of smaller ones solved the problem. (That affected only 32b builds, I think).

**Comment by jwuttke** [comment]
Jan, thank you for this background info.

This issue is about speed and simplicity. Regarding speed, we found that overall performance of Steca suffered from integer divisions and modulo computations. These operations are gone for good after conversion to 1D vector. Admittedly though, a simpler solution would have been replacing the one big loop by a double loop over the two image dimensions.

So this refactoring was more about simplification, getting rid of a home brewed solution in favor of std::. Our customers no longer need 32b.
