### ISSUE TITLE
file load dialog: nonsense message when changing directory

### ISSUE THREAD

**Issue by jwuttke** [scgmlz/Steca#82]

**Comment by JoachimCoenen** [comment]
I cannot reproduce the bug and I cannot find the corresponding message string in the source code nor the executable. Is this a problem of the operating system?

**Comment by jwuttke** [comment]
reported as upstream bug: https://bugreports.qt.io/browse/QTBUG-67866

**Comment by jwuttke** [comment]
duplicate
